apiVersion: v1
kind: Namespace
metadata:
  name: cloudbees
---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: cbinstaller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cbinstaller
  namespace: cbinstaller
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-admin
  namespace: cloudbees
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-admin
  namespace: nginx-ingress
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-admin
  namespace: cloudbees
subjects:
- kind: ServiceAccount
  name: cbinstaller
  namespace: cbinstaller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-admin
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-admin
  namespace: nginx-ingress
subjects:
- kind: ServiceAccount
  name: cbinstaller
  namespace: cbinstaller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-admin
